### PR TITLE
MWE of using pre-commit to manage pre-commit checks

### PR DESCRIPTION
**Pull request by amarburg**
A first-cut MWE of using [pre-commit](https://pre-commit.com/) to manage Git pre-commit hooks.

To "activate" pre-commit on **your** checkout, you need to:

1.  Install the Python package e.g. `pip install pre-commit`
1. In your checkout, `pre-commit install` 

To manually check all files:  `pre-commit run --all-files`, otherwise the checks will run (duh) pre-commit.

**Note:** that many of the checks (e.g. clang) will update your files automatically.  It is up to you to commit the resulting changes.

---

The config file included here runs a number basic file heuristics (whitespace at the end of files, etc), and `clang-format` with the "Google" style.  

`cpplint` is included but commented out (using it will require the time commitment to fix the resulting warnings).

For reference, this is the output when I run it manually:

Untitled

### CODE REVIEW

**Comment by amarburg** [comment]
As of right now, running pre-commit does not run in CI.   It needs to be:

1. Added to the relevant CI images
2. Explicitly called from the CI script

and ideally

3. The CI cache should be configured to save pre-commit's checkouts of the necessary tools (see [the pre-commit manual](https://pre-commit.com/#usage-in-continuous-integration))

**Comment by amarburg** [comment]
Just for simplicity, I put the messy commit containing all of the minor changes from `clang-format` and other hooks in [its own PR](https://github.com/apl-ocean-engineering/sonar_image_proc/pull/29)

**Comment by amarburg** [comment]
@micat001 @lauralindzey  per last-week's conversation I decided to check out [pre-commit](https://pre-commit.com/) to manage auto-magic pre-commit linting and formatting.   I'm reasonably impressed.

At your leisure, try this branch.   It **does not** have the suggested changes committed (see #29 ), so you can use `pre-commit run --all-files` to see before-and-after.

Concerns:
- needing to manually install it in each checkout is brittle.  The [`automatic enable` function](https://pre-commit.com/#automatically-enabling-pre-commit-on-repositories) helps a bit, but it needs to be enabled on a per-machine basis.   
- Setting up pre-commit in CI will help at least provide an error if non-checked code is commited, but it's a non-trivial lift.
- Automatic code changes should (?) have no functional consequences, but it does point out our lazy approach to automatic unit testing, etc to verify code works after being formatted.
- Questions of where/how we store our "canonical" pre-commit configuration.

**Comment by amarburg** [comment]
Ha ha.  I modified our ROS-CI process to check for a `.pre-commit-config.yaml` file.... and it works!   But this branch doesn't pass the CI check (because it doesn't contain the "fixes" from pre-commit).   Sadness.

**Comment by lauralindzey** [comment]
This is officially really cool. I'm sorry it took me so long to get around to looking at this PR. I was just telling @micat001 this morning that I wished we had auto-linting set up .... and here you've started down that path!

**Pull request merged**
